### PR TITLE
Fix/ checkbox unchecked when praise score changes

### LINKED ISSUE #353: On QuantifyTable, when moving slider to 0, checkbox is visually unchecked
On QuantifyTable, when moving slider to 0, checkbox is visually unchecked

**Steps to reproduce**
- Move slider to 10
- Check praise
- Move slider to 0
*praise appears unchecked, but is not removed from components state selectedPraises*

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #353

### CODE REVIEW

File: packages/frontend/src/components/InlineLabelClosable.tsx [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+interface Props {
+  text: string;
+  button?: JSX.Element;
+  className?: string;
+  onClick?: () => void;
+  onClose?: () => void;
+}
+
+export const InlineLabelClosable = ({
```
Comment (kristoferlund) [inline packages/frontend/src/components/InlineLabelClosable.tsx:13]: Nice moving this to a component!

**Review by kristoferlund — APPROVED** [review]
Looks good!
