### PR TITLE
Fix: Only one field updates reactively when submitting a SettingsForm with multiple updated fields 

### LINKED ISSUE #243: Only one field updates reactively when submitting a SettingsForm with multiple updated fields
When submitting a SettingsForm with multiple updated fields, only one update is displayed reactively in the frontend without page refresh.

**Steps to Reproduce**
- Open Settings page
- Change one setting
- Click 'Submit'
*field reflects newly updated value as expected*

- Change several settings
- click 'submit'
*only one of the fields will reflect the updated value as expected (the last one to complete its query)*

### PR DESCRIPTION
**Pull request by nebs-dev**
Changes inside settings model:
-  the way single setting field is saved
- AllSettings is now selector instead of atom
- added AllSettingIds atom

Resolves #243

### CODE REVIEW

File: packages/frontend/src/model/settings.ts [hunk 1]
```diff
@@ -44,22 +43,71 @@ export const AllSettingsQuery = selector({
...
 
-export const AllSettings = atom<Setting[]>({
+export const SingleSetting = atomFamily<SettingDto | undefined, string>({
+  key: 'SingleSetting',
+  default: undefined,
+});
+
+export const AllSettingIds = atom<string[] | undefined>({
+  key: 'SettingIdList',
+  default: undefined,
```
Comment (mattyg) [inline packages/frontend/src/model/settings.ts:53]: Should AllSettingIds default to an empty array instead of undefined? Then we don't need to allow the 'undefined' type.

Comment (mattyg) [reply packages/frontend/src/model/settings.ts:53]: actually nevermind i see that's how we're doing it with periods. Let's just keep the same implementations.

**Review by mattyg — CHANGES_REQUESTED** [review]
Looks like you still need to update the local SingleSetting with the received changes from the api. 

Currently the settings changes are not reflected in the recoil state:
- change two settings, click submit
- navigate to another page
- navigate back to the settings page
*changes to settings are not reflected*
- refresh the page
*changes to settings are reflected*

**Comment by nebs-dev** [comment]
> Looks like you still need to update the local SingleSetting with the received changes from the api.
> 
> Currently the settings changes are not reflected in the recoil state:
> 
> * change two settings, click submit
> * navigate to another page
> * navigate back to the settings page
>   _changes to settings are not reflected_
> * refresh the page
>   _changes to settings are reflected_
> 
> Otherwise the changes you made look good!

thanks.. i pushed new changes - updated SingleSettings and now that is fixed
But i introduced another bug, something strange is happening with period settings, i will take a look at that also

File: packages/frontend/src/model/settings.ts [hunk 2]
```diff
@@ -109,22 +141,11 @@ export const useSetSetting = (): useSetSettingReturn => {
...
-          const updatedAllSettings = allSettings.slice();
-          updatedAllSettings.splice(settingIndex, 1, updatedSetting);
-
-          set(AllSettings, updatedAllSettings);
+        if (response.data) {
+          set(SingleSetting(setting._id), response.data);
         }
 
-        toast.success(`Saved setting "${updatedSetting.label}"`);
+        toast.success(`Saved setting "${response.data.label}"`);
```
Comment (mattyg) [inline packages/frontend/src/model/settings.ts]: Should this be moved in the conditional above? I.e. only display the success notice if `response.data` is truthy and the local setting is updated?

**Review by mattyg — APPROVED** [review]
:fire: :boom: :100:
